name: Build Accessories

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    name: ${{ matrix.name }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - name: Windows 64-bit
            os: windows-latest
            target: Win64

          - name: Android 32-bit
            os: ubuntu-latest
            target: Android32

          - name: Android 64-bit
            os: ubuntu-latest
            target: Android64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Geode mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: given
          target: ${{ matrix.target }}
          build-config: Release

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: Accessories-${{ matrix.target }}
          path: ${{ steps.build.outputs.build-output }}/*.geode
          if-no-files-found: error